In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('./Data/gurgaon_properties.csv')

In [4]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,area
3392,3 BHK Flat in Sector 83 Gurgaon,flat,vatika gurgaon,1.25 Crore,6313.0,Super Built up area 1980(183.95 sq.m.),3,3,2,servant room,"1024, Sector 83 Gurgaon, Gurgaon, Haryana",2.0,West,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",Looking for a 3 bhk property for sale in gurga...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4.5 out ...",NaN
3563,3 Bedroom House for sale in Sushant Lok Phase 1,house,sushant lok 1 builder floors,1.95,10077.0,Plot area 215(179.77 sq.m.),3,4,3+,servant room,"C Block Small Nos, Sushant Lok Phase 1, Gurgao...",4.0,West,0 to 1 Year Old,"['Huda city centre metro station', 'Sector 42-...",Brand new builder floor at very reasonable pri...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment5 out of 5', 'Lifestyle5 out of 5...",1935.0
2446,2 BHK Flat in Palam Vihar,flat,ansals duplex flat,95 Lac,7307.0,Carpet area: 1300 (120.77 sq.m.),2,3,2,study room,"A 386 A, Palam Vihar, Gurgaon, Haryana",1.0,North-East,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Location and safe surrounding . The place is n...,"['4 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Feng Shui / Vaastu Compliant', 'Water Storag...","['Safety4 out of 5', 'Lifestyle5 out of 5', 'E...",NaN
1986,3 BHK Flat in Sector 67 Gurgaon,flat,ireo victory valley,3.05 Crore,12650.0,Super Built up area 2411(223.99 sq.m.)Carpet a...,3,3,3+,servant room,"Tower B, Sector 67 Gurgaon, Gurgaon, Haryana",21.0,South-West,1 to 5 Year Old,"['AIPL Joy Street Mall', 'Golf Course Extensio...",Ireo victory valley unit for sale on very urge...,"['1 Water Purifier', '9 Fan', '1 Exhaust Fan',...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of...",NaN
2548,3 BHK Flat in Sector 83 Gurgaon,flat,vatika lifestyle homes,1.15 Crore,8214.0,Super Built up area 1832(170.2 sq.m.)Carpet ar...,3,3,1,not available,"Block A, Sector 83 Gurgaon, Gurgaon, Haryana",7.0,South-West,5 to 10 Year Old,"['Sapphire 83 Mall', 'NH – 08', 'Knowledge Tre...",For the actual picture please let us know if t...,"['3 Wardrobe', '2 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4 out ...",NaN

In [5]:
df.shape

(3972, 20)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3972 entries, 0 to 3971
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3972 non-null   object
 1   property_type    3972 non-null   object
 2   society          3402 non-null   object
 3   price            3952 non-null   object
 4   price_per_sqft   3941 non-null   float64
 5   areaWithType     3972 non-null   object
 6   bedRoom          3972 non-null   int64
 7   bathroom         3972 non-null   int64
 8   balcony          3972 non-null   object
 9   additionalRoom   3972 non-null   object
 10  address          3961 non-null   object
 11  floorNum         3951 non-null   float64
 12  facing           2788 non-null   object
 13  agePossession    3971 non-null   object
 14  nearbyLocations  3761 non-null   object
 15  description      3972 non-null   object
 16  furnishDetails   2932 non-null   object
 17  features         3256 non-null   object
 18  rating           3519 non-null   object
 19  area             945 non-null    float64
dtypes: float64(3), int64(2), object(15)
memory usage: 620.8+ KB

In [7]:
df.isnull().sum()

property_name         0
property_type         0
society             570
price                20
price_per_sqft       31
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1184
agePossession         1
nearbyLocations     211
description           0
furnishDetails     1040
features            716
rating              453
area               3027
dtype: int64

In [8]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [9]:
df['sector'] = df['sector'].str.lower()

In [10]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     90
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     81
sector 37d                                                    69
sector 83                                                     69
sector 104                                                    67
sector 86                                                     67
sector 107                                                    60
sector 108                                                    59
sector 95                                                     58
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 70                                                     53
nirvana country                                               53
sector 37c                                                    53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
sector 113                                                    43
dlf phase 2                                                   43
dlf phase 1                                                   43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
laxman vihar                                                  27
sector 54                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 67a                                                    22
dlf phase 3                                                   22
sector 111                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 62                                                     17
sector 91                                                     17
sector 110                                                    16
sector 99                                                     16
sushant lok phase 3                                           16
sector 14                                                     15
sector 63                                                     15
gwal pahari                                                   15
sector 60                                                     15
rajendra park                                                 14
sector 3                                                      14
sector 52                                                     14
sector 1 imt manesar                                          14
sector 76                                                     14
dlf phase 5                                                   14
sector 53                                                     14
sector 31                                                     13
sector 46                                                     13
sector 36a                                                    13
laxman vihar phase 2                                          13
sector 50                                                     13
sector 38                                                     12
sector 93                                                     12
sohna road                                                    12
uppals southend                                               12
sector 39                                                     12
sector 47                                                     11
sector 95a                                                    11
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
sector 55                                                      9
sector 4                                                       9
ashok vihar phase 2                                            9
south city 1                                                   9
sector 10a                                                     8
sector 43                                                      8
sector 40                                                      8
sector 89 a                                                    8
sector 57                                                      8
sector 59                                                      8
dwarka expressway                                              8
palam vihar extension                                          8
malibu town                                                    8
mehrauli  road                                                 8
c block sushant lok phase 1                                    8
sector 1                                                       7
sector 51                                                      7
sector 11                                                      7
new colony                                                     7
sector 26                                                      7
sector 58                                                      7
surat nagar 1                                                  7
sector 36 sohna                                                7
mianwali colony                                                7
jyoti park                                                     6
jacobpura                                                      6
sector 5                                                       6
rajiv nagar                                                    6
ashok vihar                                                    6
sector 23a                                                     5
subhash nagar                                                  5
chakkarpur                                                     5
sector 105                                                     5
saraswati vihar                                                5
manesar                                                        5
sector 80                                                      5
greenwood city                                                 5
new palam vihar                                                5
dayanand colony                                                5
sector 9                                                       5
sushant lok phase 2                                            5
arjun nagar                                                    5
ansal plaza                                                    5
sector 28                                                      5
sector 30                                                      5
sector 2                                                       5
sector 12a                                                     4
garhi harsaru                                                  4
suncity                                                        4
devilal colony                                                 4
imt manesar                                                    4
shivaji nagar                                                  4
bhondsi                                                        4
valley view estate                                             4
surya vihar                                                    4
sector 17                                                      4
sector 3a                                                      4
ravi nagar                                                     4
madanpuri                                                      4
new                                                            4
baldev nagar                                                   4
adarsh nagar                                                   4
sector 6                                                       4
shivpuri                                                       4
sector 12                                                      4
krishna colony                                                 4
sector 45                                                      4
sector 36                                                      4
vishnu garden                                                  4
bhim nagar                                                     4
dharam colony                                                  4
gandhi nagar                                                   3
sector 73                                                      3
a block sushant lok phase 1                                    3
sector 110 a                                                   3
shakti nagar                                                   3
sector 15                                                      3
sector 27                                                      3
mg road                                                        3
patel nagar                                                    3
b block sushant lok phase 1                                    3
maruti kunj                                                    3
sector 17a                                                     3
laxmi garden                                                   3
sector-2 sohna                                                 3
sector 8                                                       3
prem nagar                                                     3
sector 17b                                                     3
sector 88b                                                     3
sector 23                                                      3
golf course road                                               2
hira nagar                                                     2
west rajiv nagar                                               2
sheetla colony                                                 2
block a surya vihar                                            2
rosewood                                                       2
acharya puri                                                   2
sispal vihar                                                   2
nars                                                           2
surat nagar phase 2                                            2
manohar nagar                                                  2
bhawani enclave                                                2
sector 32                                                      2
new palam vihar phase 1                                        2
mayfield garden                                                2
pratap nagar                                                   2
golf course ext road                                           2
rajiv chowk                                                    2
faridabad road                                                 2
new basti                                                      2
sector 15 part 1                                               2
new palam vihar phase 2                                        2
sector-11 sohna                                                2
samaspur                                                       2
ambience island                                                2
surat nagar                                                    2
, delhi ncr                                                    2
sector 21                                                      2
shanti nagar                                                   2
sushant lok                                                    2
iffco chowk                                                    2
sohna  road                                                    2
lajpat nagar                                                   2
shankar vihar                                                  2
sector 24                                                      2
sector 41                                                      2
bissar                                                         2
daulatabad                                                     2
mohan nagar                                                    2
farukhnagar                                                    2
sector 15 part 2                                               2
sai kunj                                                       1
g block dlf city phase 1                                       1
jacobpura near sadar bazar                                     1
tekchand nagar                                                 1
laxman vihar, railway road,                                    1
bptp                                                           1
naharpur rupa                                                  1
saraswati enclave                                              1
damdma                                                         1
block h ashok vihar phase iii extension                        1
old delhi road, opp sector-14                                  1
ram nagar                                                      1
sector-7 hous                                                  1
sadar bazar                                                    1
sector 21a faridabad                                           1
begampur khatola                                               1
new colony, sector 7                                           1
b1 block sector 57                                             1
pataudi road                                                   1
sector 37b                                                     1
saroop garden rajendra park                                    1
heritage city                                                  1
mahavir pura                                                   1
sector 17c                                                     1
sector 5 chowk                                                 1
cyber city                                                     1
huda saraswati vihar                                           1
block g sector-57                                              1
ashok vihar phase i                                            1
laxmna vihar, phase 2                                          1
sector 4 urban estate                                          1
hno 13 sagar enclave sura                                      1
urban estate, sector 5                                         1
jat colony,fazilpur/taj nagar road                             1
near pataudi chowk                                             1
part 3 sector 5                                                1
sultanpur                                                      1
hsiidc plot sector 1 imt manesar                               1
ravi nager basai road                                          1
sector 37a                                                     1
kheri                                                          1
civil l                                                        1
bhora kalan                                                    1
near euro                                                      1
devi lal colony gali no 12 gurgaon nr omkar public school      1
carterpuri village                                             1
dhankot                                                        1
ansal's palam vihar                                            1
bhimgarh kheri phase 3                                         1
garauli kalan                                                  1
gopal nagar, garhi ghasita, sonipat                            1
v block dlf phase 3                                            1
south city                                                     1
khandsa                                                        1
vir nagar                                                      1
kanahi                                                         1
park view                                                      1
mahalaxmi garden, rajendra place                               1
sector-5 sohna                                                 1
ats marigold                                                   1
sector 42                                                      1
sector 9b                                                      1
near sector 1 market                                           1
sector 13                                                      1
nirvana country pocket h                                       1
new jyoti park                                                 1
ashok vihar phase 3                                            1
rajiv colony                                                   1
sec 3 bhim vihar part 1 bhimgher kheri                         1
om nagar                                                       1
godrej aria , sector 79 ,                                      1
sector-5 sheetla colony                                        1
anand garden, sector-105                                       1
near khandsa road                                              1
sector-35 sohna                                                1
alipur                                                         1
rattan garden                                                  1
near nand hospital                                             1
udyog vihar phase 1                                            1
lucknow                                                        1
shivji park colony                                             1
Name: count, dtype: int64

In [11]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [12]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [13]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [14]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [15]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [16]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [17]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [18]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [19]:
df['sector'].value_counts()

sector
sohna road              175
sector 102              113
sector 85               110
sector 92               104
sector 69                94
sector 90                90
sector 81                90
sector 65                90
sector 109               88
sector 79                81
sector 104               74
sector 83                69
sector 37d               69
sector 86                67
sector 50                66
sector 107               60
sector 108               59
sector 95                58
sector 56                57
sector 89                56
sector 48                56
sector 2                 55
sector 70a               54
sector 70                53
sector 37c               53
sector 43                53
sector-33 sohna road     51
sector 84                51
sector 26                50
sector 67                48
sector 49                48
sector 28                47
sector 66                46
sector 103               45
sector 25                43
sector 113               43
sector 61                42
sector 82                42
sector 7                 39
sector 106               38
sector 4                 36
sector 99a               32
sector 54                31
sector 12                30
sector 68                30
sector 72                29
sector 77                29
sector 71                27
sector 5                 26
sector 57                24
sector 112               24
sector 24                24
sector 33                23
sector 14                23
sector 105               23
sector 88a               23
sector 67a               22
sector 111               22
sector 11                21
sector 22                20
sector 82a               20
sector 3                 20
sector 47                19
gwal pahari              19
sector 78                19
sector 63a               18
sector 74                18
sector 91                17
sector 62                17
sector 99                16
sector 110               16
sector 60                15
sector 63                15
sector 76                14
sector 1 manesar         14
sector 53                14
sector 55                14
sector 52                14
sector 9                 13
sector 6                 13
sector 36a               13
sector 46                13
sector 4 phase 2         13
sector 31                13
sector 39                12
sector 38                12
sector 93                12
sector 9a                11
sector 95a               11
sector 41                11
sector 13                10
sector 1a manesar        10
sector 45                 9
manesar                   9
sector 89 a               8
sector 2 extension        8
c block sector 43         8
dwarka expressway         8
sector 10a                8
sector 8                  8
sector 40                 8
sector 23                 8
sector 17                 8
sector 59                 8
sector 51                 7
sector 36 sohna road      7
sector 58                 7
sector 1                  7
sector 21                 6
sector 30                 5
new sector 2              5
sector 80                 5
sector 23a                5
new                       4
sector 3a                 4
sector 12a                4
sector 36                 4
sector 110 a              3
sector 73                 3
a block sector 43         3
sector 15                 3
sector 27                 3
sector-2 sohna road       3
b block sector 43         3
sector 17b                3
patel nagar               3
maruti kunj               3
sector 17a                3
sector 88b                3
Name: count, dtype: int64

In [20]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [21]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [22]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,area
1230,2 BHK Flat in New Gurgaon,flat,green court,new,38 Lac,5507.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN,NaN
2255,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4 Crore,11428.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN,NaN
2906,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,67 Lac,5583.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN,NaN
3632,4 BHK Flat in New Gurgaon,flat,sare homes,new,85 Lac,4786.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN,NaN

In [23]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [24]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,area
401,3 Bedroom House for sale in New Palam Vihar,house,NaN,new sector 2,1.0,8796.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",1137.0
735,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,22 Lac,4400.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",NaN
2033,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.6 Crore,26936.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",NaN
3124,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5...",270.0
3226,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,28.5 Lac,3166.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ...",NaN

In [25]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [26]:
df.shape

(3816, 21)

In [27]:
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [28]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)